arch_root: /mnt

# These are aliases that define file names with group vars for specific machine.
# The name is obtained from `ansible_product_name` fact and matched to
# corresponding file in `group_vars`.
machine_aliases:
  VirtualBox: vbox.yml
  Gazelle Professional: gzp.yml
  XPS 13 9350: xps.yml

country: United States
locales:
  - en_US
  - uk_UA

user:
  name: zoresvit
  comment: Ruslan Kiianchuk
  group: zoresvit
  groups:
    - sys
    - video
    - wheel
    - systemd-journal
  shell: /bin/bash
  email: ruslan.kiianchuk@gmail.com

extra_packages:
  - keepassxc
  - mlocate
  - vlc
  - rxvt-unicode
  - bash-completion
  - goldendict
  - vim

  # Filesystem
  - dosfstools
  - hfsprogs
  - ntfs-3g
  - exfat-utils

  # Archives
  - zip
  - unzip
  - p7zip
  - unrar

extra_aur_packages:
  - cower
  - downgrade
  - pacaur
  - google-chrome

dotfiles_repo: "https://github.com/zoresvit/dotfiles"
dotfiles_install_cmd: "stow -S bash chrome conky git goldendict gtk mime python tmux urxvt vim xmonad xorg"
dotfiles_deps:
  - conky
