---
- hosts: localhost
  name: configure Arch Linux system
  connection: local
  become: yes

  pre_tasks:
    - include_vars: "group_vars/{{ machine_aliases[ansible_product_name] }}"

    - name: update repository mirrors
      command: reflector --sort score -p https --country '{{ country }}' --save /etc/pacman.d/mirrorlist

    - name: enable time sync
      command: timedatectl set-ntp true

    # Avoid interactive password prompts while installing AUR packages.
    - name: set nopasswd for makepkg
      lineinfile:
        path: /etc/sudoers
        state: present
        line: '{{ user.name }} ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

  roles:
    - pacman
    - xorg

    # Network
    - networkmanager
    - ssh

    # Desktop
    - lxdm
    - xmonad
    - laptop
    - desktop

  post_tasks:
    - name: remove nopasswd for makepkg
      lineinfile:
        path: /etc/sudoers
        state: absent
        line: '{{ user.name }} ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
