---
- name: install sound utils
  pacman: name={{ item }} state=present
  with_items:
    - alsa-utils
    - pulseaudio
    - pulseaudio-alsa
    - pulseaudio-jack
    - pavucontrol
    - pavucontrol
    - pamixer
    - paprefs

- aur: name={{ item }} user={{ user.name }}
  with_items:
    - paman
    - pasystray-gtk2-standalone

- name: Switch output to newly connected devices
  lineinfile:
    dest: /etc/pulse/default.pa
    state: present
    line: "load-module module-switch-on-connect"
