---
- name: check if dotfiles exist
  stat:
    path: "${HOME}/dotfiles"
  become_user: "{{ user.name }}"
  register: dotfiles

- name: clone dotfiles
  command: "git clone {{ dotfiles.repo }} ${HOME}/dotfiles"
  become_user: "{{ user.name }}"
  when: not dotfiles.stat.exists

- name: install dotfiles dependencies
  pacman:
    name: "{{ item }}"
    state: present
  with_items: "{{ dotfiles.deps }}"
  become_user: "{{ user.name }}"

- name: install dotfiles
  command: "{{ dotfiles.install_cmd }}"
  become_user: "{{ user.name }}"
