---
- name: check if dotfiles exist
  stat:
    path: "${HOME}/dotfiles"
  become_user: "{{ user.name }}"
  register: dotfiles_dir

- name: clone dotfiles
  command: "git clone {{ dotfiles.repo }} ${HOME}/dotfiles"
  become_user: "{{ user.name }}"
  when: not dotfiles_dir.stat.exists

- name: install dotfiles dependencies
  pacman:
    name: "{{ item }}"
    state: present
  with_items: "{{ dotfiles.deps }}"

- name: install dotfiles
  command: "{{ dotfiles.install_cmd }}"
  become_user: "{{ user.name }}"

- name: add bash dotfiles to .bashrc
  lineinfile:
    path: /home/{{ user.name }}/.bashrc
    line: 'source ${HOME}/.bashrc.local'
    create: yes
