---

- import_tasks: xorg.yml
- import_tasks: lxdm.yml
- import_tasks: themes.yml
- import_tasks: media.yml
- import_tasks: networkmanager.yml
- import_tasks: bluetooth.yml
- import_tasks: ssh.yml

- name: install cron
  pacman: name=cronie state=present
  notify:
    - enable cron

- name: install packages for desktop environment from repo
  pacman: name={{ item }}
  with_items:
    - compton
    - feh
    - redshift
    - stalonetray
    - xmobar
    - xmonad
    - xmonad-contrib
    - dunst
    - dmenu
    - deepin-screenshot
    - geeqie

- name: enable redshift service
  command: systemctl --user enable redshift.service
  become_user: "{{ user.name }}"

- import_tasks: extra_packages.yml
- import_tasks: dotfiles.yml
