- name: install udiskie for automount
  pacman: name=udiskie state=present

- name: install pmount
  aur: name=pmount user={{ user.name }}

- name: ensure /media mount dir exists
  file: path=/media state=directory

- include: media.yml

- name: install extra packages from repo
  pacman: name={{ item }} state=present
  with_items: "{{ extra_packages }}"

- name: install extra packages from AUR
  aur: name={{ item }} user={{ user.name }}
  with_items: "{{ extra_aur_packages }}"

- name: install host-specific packages from repo
  pacman: name={{ item }} state=present
  with_items: "{{ host_extra_packages }}"
  when: host_extra_packages is defined

- name: install host-specific packages from AUR
  aur: name={{ item }} user={{ user.name }}
  with_items: "{{ host_extra_aur_packages }}"
  when: host_extra_aur_packages is defined
