---

- name: install packages for desktop environment from repo
  pacman: name={{ item }}
  with_items:
    - compton
    - feh
    - redshift
    - stalonetray
    - xmobar
    - xmonad
    - xmonad-contrib

- name: install packages for desktop environment from AUR
  pacman: name={{ item }}
  with_items:
    - albert

- include: media.yml

- name: install extra packages from repo
  pacman: name={{ item }}
  with_items: "{{ extra_packages }}"

- name: install extra packages from AUR
  aur: name={{ item }} user={{ user.name }}
  with_items: "{{ extra_aur_packages }}"

- name: install host-specific packages from repo
  pacman: name={{ item }}
  with_items: "{{ host_extra_packages }}"
  when: host_extra_packages is defined

- name: install host-specific packages from AUR
  aur: name={{ item }} user={{ user.name }}
  with_items: "{{ host_extra_aur_packages }}"
  when: host_extra_aur_packages is defined

