
- include: media.yml
- include: audio.yml

- name: install cronie
  pacman: name=cronie state=present
  notify:
    - enable cron

- name: install packages for desktop environment
  pacman: name={{ item }} state=present
  with_items:
    - mate-notification-daemon
    - gnome-screensaver
    - rxvt-unicode
    - stow
    - keepassxc
    - xmobar
    - stalonetray
    - conky
    - python-pip
    - gvim
    - compton
    - vlc

- name: install extra packages
  pacman: name={{ item }} state=present
  with_items: "{{ extra_packages }}"

- name: install extra AUR packages
  aur: name={{ item }} user={{ user.name }}
  with_items: "{{ extra_aur_packages }}"
