---

- import_tasks: xorg.yml
- import_tasks: lxdm.yml
- import_tasks: media.yml
- import_tasks: networkmanager.yml
- import_tasks: bluetooth.yml
- import_tasks: ssh.yml

- name: install cron
  pacman: name=cronie state=present
  notify:
    - enable cron

- name: install packages for desktop environment from repo
  pacman: name={{ item }}
  with_items:
    - compton
    - feh
    - redshift
    - stalonetray
    - xmobar
    - xmonad
    - xmonad-contrib

- import_tasks: extra_packages.yml

- name: clone dotfiles
  command: "git clone {{ dotfiles.repo }} ${HOME}/dotfiles"
  become_user: "{{ user.name }}"

- name: install dotfiles dependencies
  pacman:
    name: "{{ item }}"
    state: present
  with_items: "{{ dotfiles.deps }}"
  become_user: "{{ user.name }}"

- name: install dotfiles
  command: "{{ dotfiles.install_cmd }}"
  become_user: "{{ user.name }}"
