
- include: audio.yml

- name: install packages for desktop environment
  pacman: name={{ item }} state=present
  with_items:
    - mate-notification-daemon
    - gnome-screensaver
    - rxvt-unicode
    - stow
    - keepassxc
    - xmobar
    - stalonetray
    - conky
    - python-pip
    - gvim
    - compton
    - vlc

