---
- name: install udiskie packages for automount
  pacman: name={{ item }} state=present
  with_items:
    - udiskie

- name: install pmount
  aur: name=pmount user={{ user.name }}

- name: ensure /media mount dir exists
  file: path=/media state=directory

- name: install media codecs and helpers
  pacman: name={{ item }} state=present
  with_items:
    - flac
    - lame
    - gst-libav
    - gst-plugins-good
    - exiv2
    - perl-image-exiftool
    - opus-tools
