---
- name: install Xorg server
  pacman: name={{ item }} state=present
  with_items:
    - xorg
    - xterm
    - notification-daemon
    - xf86-input-libinput

- name: configure input devices
  copy: src=xorg/30-input.conf dest=/etc/X11/xorg.conf.d/30-input.conf

- name: add user to video group
  user: name={{ user.name }} groups=video append=yes

- name: install GTK and Qt themes
  pacman: name={{ item }} state=present
  with_items:
    - qt4
    - qt5-base
    - qt5ct
    - breeze
    - breeze-gtk
    - breeze-kde4
    - breeze-icons
    - gnome-themes-standard

- name: install events sound interface
  pacman: name={{ item }} state=present
  with_items:
    - libcanberra
    - libcanberra-pulse
    - sound-theme-freedesktop

- name: install fonts
  pacman: name={{ item }} state=present
  with_items:
    - ttf-hack
    - ttf-dejavu

- name: configure GTK 2
  copy:
    src: gtk-2.0/gtkrc
    dest: /etc/gtk-2.0/gtkrc

- name: configure GTK 3
  copy: src=gtk-3.0/settings.ini dest=/etc/gtk-3.0/settings.ini

- name: set main window background color for GTK 3
  copy:
    src: gtk-3.0/gtk.css
    dest: /etc/gtk-3.0/gtk.css

- name: configure Qt 4
  copy:
    src: qt/Trolltech.conf
    dest: /etc/xdg/Trolltech.conf

- name: configure Qt 5
  copy:
    src: qt/qt5ct.conf
    dest: /home/{{ user.name }}/.config/qt5ct/qt5ct.conf
    owner: "{{ user.name }}"

- name: configure cursor
  lineinfile:
    path: /usr/share/icons/default/index.theme
    regexp: ^Inherits=
    line: Inherits=Breeze_Snow

# TODO: check if xbacklight works without out of the box.
#- name: install acpilight from AUR
#  aur: name={{ item }} user={{ user.name }}
#  with_items:
#    - acpilight
