---
default_packages:
  - linux-firmware
  - mlocate
  - reflector

  # Filesystem
  - dosfstools
  - hfsprogs
  - ntfs-3g
  - exfat-utils

  # Archives
  - zip
  - unzip
  - p7zip
  - unrar

default_aur_packages:
  - cower
  - downgrade
  - pacaur

aur_gpg_trusted_keys: []
gpg_keyserver: "hkp://pgp.mit.edu"
