---
- name: install Xorg server
  pacman: name={{ item }} state=present
  with_items:
    - xf86-input-libinput
    - xorg
    - xorg-apps
    - xterm

- name: configure scrolling
  copy: src=30-scrolling.conf dest=/etc/X11/xorg.conf.d/

- name: configure touchpad
  copy: src=30-touchpad.conf dest=/etc/X11/xorg.conf.d/

- name: configure keyboard
  copy: src=30-keyboard.conf dest=/etc/X11/xorg.conf.d/

- name: add user to video group
  user: name={{ user.name }} groups=video append=yes

- name: install extra packages
  pacman: name={{ item }} state=present
  with_items:
    - xclip
    - mate-notification-daemon

- name: install extra AUR packages
  aur: name={{ item }} user={{ user.name }}
  with_items:
    - acpilight
