---
- name: install pulseaudio
  pacman: name={{ item }} state=present
  with_items:
    - alsa-utils
    - pulseaudio
    - pulseaudio-alsa
    - pulseaudio-jack
    - pavucontrol
    - pamixer
    - paprefs

- name: install audio management utilities from AUR
  aur: name={{ item }} user={{ user.name }}
  with_items:
    - paman
    - pasystray-gtk3-standalone

- name: configure to switch audio output to newly connected devices
  lineinfile:
    dest: /etc/pulse/default.pa
    state: present
    line: "load-module module-switch-on-connect"
