---

- name: install stow to manage symlinks
  pacman: name=stow

- name: clone dotfiles repo
  command: git clone {{ dotfiles_repo }} ~/dotfiles

- name: install dotfiles
  command: chdir=~/dotfiles {{ dotfiles_install_cmd }}
