---
- name: install SSH related packages
  pacman: name={{ item }} state=present update_cache=yes
  with_items:
    - openssh
    - keychain

- name: stop SSH daemon if already running
  service: name=sshd state=stopped
  ignore_errors: yes

- name: configure SSH daemon
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config backup=yes
  notify:
    - enable sshd
