---
- name: install SSH related packages
  pacman: name={{ item }} state=present update_cache=yes
  with_items:
    - openssh
    - keychain

- name: push OpenSSH daemon configuration file
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config backup=yes
  notify:
    - enable sshd
