---
- name: install NetworkManager and dependencies
  pacman: name={{ item }} state=present
  with_items:
      - networkmanager
      - networkmanager-openvpn
      - network-manager-applet
      - gnome-keyring

- name: enable NetworkManager
  service: name=NetworkManager.service enabled=yes state=started

- name: configure mirrors update hook
  copy:
    src: mirrors-hook.sh
    dest: /etc/NetworkManager/dispatcher.d/99update-mirrors.sh
