---

- name: configure repository mirrors
  command: reflector --sort score -p https --country '{{ country }}' --save /etc/pacman.d/mirrorlist

- name: upgrade system to latest state
  pacman: update_cache=yes upgrade=yes

- include: locales.yml

- name: set console font
  lineinfile: dest=/etc/vconsole.conf state=present create=yes line="FONT=Lat2-Terminus16"

- name: configure hostname
  lineinfile: dest=/etc/hostname create=yes line='{{ hostname }}'

- name: set hostname in /etc/hosts file
  template: src=hosts.j2 dest=/etc/hosts mode=644

- name: install base packages
  pacman: name={{ item }} state=present
  with_items: "{{ packages }}"

- include: user.yml
- include: bootloader.yml
