hostname: localhost
timezone: America/Los_Angeles
country: United States
locales:
  - en_US

initramfs_hooks:
  - base
  - udev
  - autodetect
  - modconf
  - keyboard
  - block
  - encrypt
  - filesystems
  - keyboard
  - fsck

packages:
  - arch-wiki-lite
  - coreutils
  - dialog
  - glances
  - linux-firmware
  - lsof
  - moreutils
  - rsync
  - sysstat
  - wpa_supplicant
