---
- name: restart cron
  service: name=cronie.service state=restarted

- name: rebuild grub
  command: grub-mkconfig -o /boot/grub/grub.cfg

- name: reload systemd config
  command: systemctl daemon-reload

- name: restart paccache
  service: name=paccache.timer state=restarted
