hostname: gzp

host_extra_packages: []
host_extra_aur_packages: []

drive:
  device: /dev/disk/by-id/ata-INTEL_SSDSC2BW120A4_CVDA336001ZK1207GN
  table: gpt
  partitions:

    - name: bios_grub
      start: 1MiB
      end: 512MiB
      flags: [bios_grub]
      encrypt: false

    - name: root
      start: 512MiB
      end: 50GiB
      filesystem: ext4
      mountpoint: /
      encrypt: true

    - name: var
      start: 50GiB
      end: 100%
      filesystem: ext4
      mountpoint: /var
      encrypt: true
