hostname: gazp

disk:
  device: /dev/disk/by-uuid/ata-INTEL_SSDSC2BW120A4_CVDA336001ZK1207GN
  table: gpt
  partitions:

    - name: bios_grub
      start: 1MiB
      end: 3MiB
      type: bios_grub

    - name: boot
      start: 3MiB
      end: 256MiB
      fstype: ext4
      mountpoint: /boot

    - name: lvm
      start: 256MiB
      end: 100%
      lvm_group: arch

encrypt_partition: "{{ disk.partitions[2].name }}"

lvm:
  group: arch
  volumes:

    - name: root
      size: 20G
      fstype: ext4
      mountpoint: /

    - name: var
      size: 10G
      fstype: ext4
      mountpoint: /var

    - name: swap
      size: 1G
      fstype: linux-swap

    - name: home
      size: 100%FREE
      fstype: ext4
      mountpoint: /home

