hostname: vbox

host_extra_packages:
  - nvidia-340xx-utils
  - virtualbox-guest-modules-arch
  - virtualbox-guest-utils

# UEFI/GPT
drive:
  device: /dev/sda
  table: gpt
  partitions:

    - name: root
      start: 512MiB
      end: 100%
      filesystem: ext4
      mountpoint: /
      encrypt: true

    - name: efi
      start: 0%
      end: 512MiB
      flags: [boot]
      filesystem: vfat
      mountpoint: /boot/efi
      encrypt: false

# BIOS/GPT
#disk:
#  device: /dev/sda
#  table: gpt
#  partitions:
#
#    - name: bios_grub
#      start: 1MiB
#      end: 3MiB
#      flags: bios_grub
#      encrypt: false
#
#    - name: boot
#      start: 3MiB
#      end: 512MiB
#      type: primary
#      filesystem: ext4
#      mountpoint: /boot
#      encrypt: false
#
#    - name: root
#      start: 512MiB
#      end: 100%
#      filesystem: ext4
#      mountpoint: /
#      encrypt: true
