hostname: xps

host_extra_aur_packages:
  - bcm4350-firmware

disk:
  device: /dev/sda
  table: gpt
  partitions:

    - name: boot
      start: 1MiB
      end: 256MiB
      fstype: ext4
      mountpoint: /boot

    - name: efi
      start: 256MiB
      end: 512MiB
      type: EPS
      fstype: vfat
      mountpoint: /boot/efi

    - name: lvm
      start: 512MiB
      end: 100%
      lvm_group: arch

encrypt_partition: "{{ disk.partitions[2].name }}"

lvm:
  - group: arch
    volumes:
      - name: root
        size: 30G
        fstype: ext4
        mountpoint: /

      - name: var
        size: 20G
        fstype: ext4
        mountpoint: /var

      - name: home
        size: 100%FREE
        fstype: ext4
        mountpoint: /home
