---
- name: install additional drivers
  pacman: name={{ item }} state=present update_cache=yes upgrade=yes
  with_items: "{{ drivers }}"
  when: drivers is defined

- name: install intel microcode
  pacman: name=intel-ucode state=present
  notify:
    - rebuild grub
  when: "'GenuineIntel' in ansible_processor"

- name: install udev rule for IO scheduler
  copy: src=udev/scheduler.rules dest=/etc/udev/rules.d/20-scheduler.rules

- name: Enable systemd-timesyncd
  command: timedatectl set-ntp true

- name: install cronie
  pacman: name=cronie state=present
  notify:
    - start cron

- include: pacman.yml

- include: shell.yml
- include: media.yml

- name: install packages
  pacman: name={{ item }} state=present update_cache=yes upgrade=yes
  with_items: "{{ packages }}"

- name: retrieve trusted GPG keys for AUR
  command: gpg --recv-keys --keyserver  {{ gpg_keyserver }} {{ item }}
  become: true
  become_user: "{{ user.name }}"
  with_items: "{{ aur_gpg_trusted_keys }}"


- name: install AUR packages
  aur: name={{ item }} user={{ user.name }}
  with_items: "{{ aur_packages }}"
