---
- name: install udiskie packages for automount
  pacman: name={{ item }} state=present
  with_items:
    - udiskie

- aur: name=pmount user={{ user.name }}

- name: create /media mount dir
  file: path=/media state=directory

- name: add rule to mount removable storage to /media
  copy: src=udev/mount.rules dest=/etc/udev/rules.d/90-mount.rules

- name: install media codecs and helpers
  pacman: name={{ item }} state=present
  with_items:
    - flac
    - lame
    - gst-libav
    - gst-plugins-good
    - exiv2
    - perl-image-exiftool
    - opus-tools
